version: '3'

services:
  app:
    image: 'ecommerce:latest'
    build:
      context: .
    container_name: ecommerce-app
    ports:
      - "9898:9898"
    depends_on:
      - db
    environment:
      - SERVER_PORT=9898
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

  db:
    image: 'postgres:14-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
